#!/bin/sh -x
echo "This Script Install FEX RootFS automatically."

echo ""

echo "FEX RootFS size is almost 1gb."
echo ""

while true; do

read -p "Do you want to proceed? (y/n) " yn

case $yn in 
	[yY] ) echo Downloading ...;
		break;;
	[nN] ) echo exiting...;
		exit;;
	* ) echo invalid response;;
esac

done
  
 cd ~

  echo "Downloading Steam scripts"
  
  curl -o setup_steam.sh https://raw.githubusercontent.com/Erhannis/FEXDroid/refs/heads/fork/mistosts/setup_steam.sh
  curl -o setup_steam_2.sh https://raw.githubusercontent.com/Erhannis/FEXDroid/refs/heads/fork/mistosts/setup_steam_2.sh
  curl -o start_steam.sh https://raw.githubusercontent.com/Erhannis/FEXDroid/refs/heads/fork/mistosts/start_steam.sh

  chmod +x setup_steam.sh setup_steam_2.sh start_steam.sh

  echo ""
  echo "Downloading Ubuntu"
  echo "See https://rootfs.fex-emu.gg/RootFS_links.json if the following file is missing"
  wget -q --show-progress https://rootfs.fex-emu.gg/Ubuntu_23_04/2023-12-03/Ubuntu_23_04.sqsh
  
  echo "Download complete"
  
  echo "setting up Ubuntu_23_04 as Default RootFS"
  mv Ubuntu_23_04.sqsh $HOME/.fex-emu/RootFS/Ubuntu_23_04.sqsh
  echo ""
  
  cd $HOME/.fex-emu/RootFS
  
  echo ""
  
  echo "Extracting ..."
  unsquashfs Ubuntu_23_04.sqsh
  
  rm -rf Ubuntu_23_04.sqsh
  
  mv squashfs-root Ubuntu_23_04
  
  echo ""

  echo "Done"
  